export const leadersList = [
  {
    username: "rogers",
    date: "Oct 12, 3:52 AM",
    amount: 31450,
    avatar: "/vectors/Avatar.svg",
    imgUrl: "",
    isPositive: false,
  },
  {
    username: "Akinsola",
    date: "Oct 12, 3:52 AM",
    amount: 23450,
    avatar: "/vectors/Avatar1.svg",
    imgUrl: "",
    isPositive: false,
  },
  {
    username: "Hemsleek",
    date: "Oct 12, 3:52 AM",
    amount: 20450,
    avatar: "/vectors/Avatar2.svg",
    imgUrl: "",
    isPositive: true,
  },
  {
    username: "Muze",
    date: "Oct 12, 3:52 AM",
    amount: 30450,
    avatar: "/vectors/Avatar3.svg",
    imgUrl: "",
    isPositive: false,
  },
  {
    username: "Desmond",
    date: "Oct 12, 3:52 AM",
    amount: 19450,
    avatar: "/vectors/Avatar4.svg",
    imgUrl: "",
    isPositive: true,
  },
  {
    username: "Akinsola",
    date: "Oct 12, 3:52 AM",
    amount: 15450,
    avatar: "/vectors/Avatar5.svg",
    imgUrl: "",
    isPositive: true,
  },
  {
    username: "toyosi",
    date: "Oct 12, 3:52 AM",
    amount: 32450,
    avatar: "/vectors/Avatar1.svg",
    imgUrl: "",
    isPositive: false,
  },
  {
    username: "bobjoe",
    date: "Oct 12, 3:52 AM",
    amount: 12450,
    avatar: "/vectors/Avatar3.svg",
    imgUrl: "",
    isPositive: false,
  },
];
