import AmazonIconCircle from "../../components/atoms/vectors/AmazonIconCircle";
import AmazonLogoTiny from "../../components/atoms/vectors/AmazonLogoTiny";
import AppleLogoIcon from "../../components/atoms/vectors/AppleLogoIcon";
import CardTradeIcon from "../../components/atoms/vectors/CardTradeIcon";
import ItunesLogoTiny from "../../components/atoms/vectors/ItunesLogoTiny";
import NikeLogoSm from "../../components/atoms/vectors/NikeLogoPlain";
import SephoraLogoSm from "../../components/atoms/vectors/SephoraLogoSm";
import SteamLogoSm from "../../components/atoms/vectors/SteamLogoSm";
import WalletFundingIcon from "../../components/atoms/vectors/WalletFundingIcon";
import WalmartLogoSm from "../../components/atoms/vectors/WalmartLogoSm";
import WithdrawalIcon from "../../components/atoms/vectors/WithdrawalIcon";
import { generateId } from "../generateId";

export const today = new Date();
export const yesterday = new Date(today);

yesterday.setDate(yesterday.getDate() - 1);

export const transactionData = [
  {
    id: generateId(),
    icon: WithdrawalIcon,
    category: "Bill Payments",
    transactionTitle: "Airtime",
    type: "debit",
    product: "Airtel Refill",
    productDescription: "Airtel Airtime",
    productOrigin: "Airtel Refill",
    productOriginDesc: "09077738743",
    productIconUrl: "/vectors/AirtelLogoSquared.svg",
    transactionRefNumber: "RDMA-20210916-8457891148",
    date: today.toDateString(),
    amount: {
      currency: "₦",
      value: 1000,
    },
    status: "Successfull",
  },
  {
    id: generateId(),
    icon: AmazonIconCircle,
    category: "Gift Cards",
    transactionTitle: "Giftcard Trade",
    type: undefined,
    product: "Amazon (300-500) ",
    productOrigin: "Amazon",
    productOriginDesc: "USA Cash Receipt ($50 - $100)",
    productIconUrl: "",
    transactionRefNumber: "RDMA-20210916-8457891146",
    transactionRate: 310,
    expectedValue: 15500,
    date: today.toDateString(),
    amount: {
      currency: "₦",
      value: 100,
    },
    status: "Successfull",
  },
  {
    id: generateId(),
    icon: WithdrawalIcon,
    category: "Bill Payments",
    transactionTitle: "Airtime",
    type: "debit",
    product: "Airtel Refill",
    productDescription: "Airtel Airtime",
    productOrigin: "Airtel Refill",
    productOriginDesc: "09033438743",
    productIconUrl: "/vectors/AirtelLogoSquared.svg",
    transactionRefNumber: "RDMA-20210916-8457891148",
    date: today.toDateString(),
    amount: {
      currency: "₦",
      value: 1000,
    },
    status: "Rejected",
  },
  {
    id: generateId(),
    icon: AppleLogoIcon,
    category: "Gift Cards",
    transactionTitle: "Giftcard Trade",
    type: undefined,
    product: "iTunes (50-100) ",
    productOrigin: "iTunes",
    productOriginDesc: "USA Cash Receipt ($50 - $100)",
    productIconUrl: "",
    transactionRefNumber: "RDMA-20210916-8457891146",
    transactionRate: 310,
    expectedValue: 15500,
    date: today.toDateString(),
    amount: {
      currency: "₦",
      value: 100,
    },
    status: "Successfull",
  },
  {
    id: generateId(),
    icon: NikeLogoSm,
    category: "Gift Cards",
    transactionTitle: "Giftcard Trade",
    type: undefined,
    product: "Nike (300-500) ",
    productOrigin: "Nike",
    productOriginDesc: "USA Cash Receipt ($50 - $100)",
    productIconUrl: "",
    transactionRefNumber: "RDMA-20210916-8457891146",
    transactionRate: 310,
    expectedValue: 15500,
    date: today.toDateString(),
    amount: {
      currency: "₦",
      value: 100,
    },
    status: "Successfull",
  },
  {
    id: generateId(),
    icon: WithdrawalIcon,
    category: "Bill Payments",
    transactionTitle: "Internet",
    type: "debit",
    product: "Spectranet",
    productDescription: "Spectranet | LAGOS UNIFIED VALUE 4GB",
    productOrigin: "Spectranet",
    productOriginDesc: "Spectranet (18126804)",
    productIconUrl: "/vectors/SpectranetLogoSquared.svg",
    transactionRefNumber: "RDMA-20210916-8457891146",
    date: yesterday.toDateString(),
    amount: {
      currency: "₦",
      value: 25000,
    },
    status: "Successfull",
  },
  {
    id: generateId(),
    icon: WalmartLogoSm,
    category: "Gift Cards",
    transactionTitle: "Giftcard Trade",
    type: undefined,
    product: "Walmart ",
    productDescription: "Walmart(50-100)",
    productOrigin: "Walmart",
    productOriginDesc: "USA Cash Receipt ($50 - $100)",
    productIconUrl: "",
    transactionRefNumber: "RDMA-20210916-8457891146",
    transactionRate: 310,
    expectedValue: 15500,
    date: yesterday.toDateString(),
    amount: {
      currency: "₦",
      value: 50,
    },
    status: "Successfull",
  },
  {
    id: generateId(),
    icon: WithdrawalIcon,
    category: "Bill Payments",
    transactionTitle: "Airtime",
    type: "debit",
    product: "Airtel Refill",
    productDescription: "Airtel Airtime",
    productOrigin: "Airtel Refill",
    productOriginDesc: "09077738544",
    productIconUrl: "/vectors/AirtelLogoSquared.svg",
    transactionRefNumber: "RDMA-20210916-8457891146",
    date: today.toDateString(),
    amount: {
      currency: "₦",
      value: 1000,
    },
    status: "Pending",
  },
  {
    id: generateId(),
    icon: SephoraLogoSm,
    category: "Gift Cards",
    transactionTitle: "Giftcard Trade",
    type: undefined,
    product: "Sephora",
    productDescription: "Sephora (100-200)",
    productOrigin: "Sephora",
    productOriginDesc: "USA Cash Receipt ($50 - $100)",
    productIconUrl: "",
    transactionRefNumber: "RDMA-20210916-8457891146",
    transactionRate: 310,
    expectedValue: 15500,
    date: today.toDateString(),
    amount: {
      currency: "₦",
      value: 50,
    },
    status: "Successfull",
  },
  {
    id: generateId(),
    icon: SteamLogoSm,
    category: "Gift Cards",
    transactionTitle: "Giftcard Trade",
    type: undefined,
    product: "Steam ",
    productDescription: "Steam (50-100)",
    productOrigin: "Steam",
    productOriginDesc: "USA Cash Receipt ($50 - $100)",
    productIconUrl: "",
    transactionRefNumber: "RDMA-20210916-8457891146",
    transactionRate: 310,
    expectedValue: 15500,
    date: today.toDateString(),
    amount: {
      currency: "₦",
      value: 50,
    },
    status: "Successfull",
  },
  {
    id: generateId(),
    icon: WithdrawalIcon,
    category: "Bill Payments",
    transactionTitle: "Internet",
    type: "debit",
    product: "Spectranet",
    productDescription: "Spectranet | LAGOS UNIFIED VALUE 4GB",
    productOrigin: "Internet",
    productOriginDesc: "Spectranet (18126804)",
    productIconUrl: "/vectors/SpectranetLogoSquared.svg",
    transactionRefNumber: "RDMA-20210916-8457891146",
    date: yesterday.toDateString(),
    amount: {
      currency: "₦",
      value: 20000,
    },
    status: "Pending",
  },
  {
    id: generateId(),
    icon: WithdrawalIcon,
    category: "Bill Payments",
    transactionTitle: "Airtime",
    type: "debit",
    product: "Airtel Refill",
    productDescription: "Airtel Data",
    productOrigin: "Airtel Refill",
    productOriginDesc: "09077738544",
    productIconUrl: "/vectors/AirtelLogoSquared.svg",
    transactionRefNumber: "RDMA-20210916-8457891146",
    date: yesterday.toDateString(),
    amount: {
      currency: "₦",
      value: 5000,
    },
    status: "Rejected",
    errorMessage: "",
  },
];

export const walletTransactions = [
  {
    id: generateId(),
    icon: WithdrawalIcon,
    category: "Withdrawal",
    transactionTitle: "Withdrawal",
    type: "debit",
    product: "Wema Bank",
    productDescription:
      "Credit from | LAWAL OMOTOYOSI ADEKUNLE | NIP:LAWAL OMOTOYOSI ADEKUNLE-2070031551/7463728192 | 00000421072625422050148386214",
    productOrigin: "Wema Bank",
    productOriginDesc: "0077738544",
    productIconUrl: "/vectors/WemaBankLogo.svg",
    transactionRefNumber: "RDMA-20210916-8457891146",
    date: yesterday.toDateString(),
    amount: {
      currency: "₦",
      value: 5000,
    },
    status: "Successfull",
    errorMessage: "",
  },
  {
    id: generateId(),
    icon: WalletFundingIcon,
    category: "Wallet Funding",
    transactionTitle: "Wallet Funding",
    type: "credit",
    product: "Naira Wallet",
    productDescription:
      "Credit from | LAWAL OMOTOYOSI ADEKUNLE | NIP:LAWAL OMOTOYOSI ADEKUNLE-2070031551/7463728192 | 00000421072625422050148386214",
    productOrigin: "Wema Bank",
    productOriginDesc: "0077738544",
    productIconUrl: "/vectors/WemaBankLogo.svg",
    transactionRefNumber: "RDMA-20210916-8457891146",
    date: yesterday.toDateString(),
    amount: {
      currency: "₦",
      value: 5000,
    },
    status: "Successfull",
    errorMessage: "",
  },
];
